//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_Stripscrabble
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        public int idContrat { get; set; }
        public string idVisiteur { get; set; }
        public System.DateTime dateDebut { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
    
        public virtual Date Date { get; set; }
        public virtual Visiteur Visiteur { get; set; }
    }
}
