//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_Stripscrabble
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratoire
    {
        public Laboratoire()
        {
            this.Visiteur = new HashSet<Visiteur>();
        }
    
        public int idLabo { get; set; }
        public string nomLabo { get; set; }
        public string idDirecteur { get; set; }
    
        public virtual ICollection<Visiteur> Visiteur { get; set; }
        public virtual Visiteur VisiteurResp { get; set; }
    }
}
