//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_Stripscrabble
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPE3_StripscrabbleEntities : DbContext
    {
        public PPE3_StripscrabbleEntities()
            : base("name=PPE3_StripscrabbleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Etat> Etat { get; set; }
        public DbSet<FAMILLE> FAMILLE { get; set; }
        public DbSet<fichefrais> fichefrais { get; set; }
        public DbSet<FraisForfait> FraisForfait { get; set; }
        public DbSet<Laboratoire> Laboratoire { get; set; }
        public DbSet<LigneFraisForfait> LigneFraisForfait { get; set; }
        public DbSet<LigneFraisHorsForfait> LigneFraisHorsForfait { get; set; }
        public DbSet<MEDECIN> MEDECIN { get; set; }
        public DbSet<MEDICAMENT> MEDICAMENT { get; set; }
        public DbSet<MOTIF> MOTIF { get; set; }
        public DbSet<OFFRIR> OFFRIR { get; set; }
        public DbSet<RAPPORT> RAPPORT { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<Secteur> Secteur { get; set; }
        public DbSet<SPECIALITE> SPECIALITE { get; set; }
        public DbSet<Visiteur> Visiteur { get; set; }
    }
}
