//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_Stripscrabble
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTIF
    {
        public MOTIF()
        {
            this.RAPPORT = new HashSet<RAPPORT>();
        }
    
        public int idMotif { get; set; }
        public string libMotif { get; set; }
    
        public virtual ICollection<RAPPORT> RAPPORT { get; set; }
    }
}
